name: ci.yml
on:
  workflow_dispatch:
    inputs:
      use_secrets:
        description: 'Use secrets'
        required: true
        type: boolean
        default: false
      use_usermapp:
        description: 'Use usermapp service'
        required: true
        type: boolean
        default: false

jobs:
  buildandtest:
    if: ${{ inputs.use_secrets }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Send mail
        uses: ./
        id: mail
        with:
          api_key: ${{ secrets.MAILGUN_API_KEY }}
          domain: ${{ secrets.MAILGUN_DOMAIN }}
          from: ${{ secrets.MAILGUN_FROM }}
          to: ${{ secrets.MAILGUN_TO }}
          subject: "Functional Test mailgun sendmail"
          message: '<p>Hello World</p>'
      - name: Print outputs
        run: echo ${{ steps.mail.outputs.result }}
  usermapp:
    if: ${{ inputs.use_usermapp }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get E-Mail address of actor
        id: get_email
        run: |
          EMAIL=$(curl -X GET 'https://usermapp.sanctum.mineral-minds.net/email?github_username=${{ github.actor }}' -H 'api-key: ${{ secrets.USERMAPP_API_KEY }}')
          echo $EMAIL
          echo "USERMAPP_EMAIL=$EMAIL" >> $GITHUB_ENV
      - name: Send mail
        uses: ./
        id: mail
        with:
          api_key: ${{ secrets.MAILGUN_API_KEY }}
          domain: ${{ secrets.MAILGUN_DOMAIN }}
          from: ${{ secrets.MAILGUN_FROM }}
          to: ${{ env.USERMAPP_EMAIL }}
          subject: "Workflow Dispatch mailgun sendmail"
          message: '<p>Hello World</p>'
      - name: Print outputs
        run: echo ${{ steps.mail.outputs.result }}
